tags:
- name: sellers
  description: sellers API

paths:
# [GET] sellers
  /sellers:
    get:
      tags:
      - sellers
      summary: Find All Sellers
      description: Route responsible to obtain all sellers presents in the database
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    type: array
                    items: 
                      $ref: '#/components/schemas/seller'                
                  message:
                    type: string
        500:
          description: 'Server Error'

# [POST] sellers
    post:
      tags:
      - sellers
      summary: Add Seller
      description: Route responsible to add one seller to the database
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sellerData'
      responses:
        201:
          description: 'Created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    $ref: '#/components/schemas/seller'                
                  message:
                    type: string
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] sellers/id
  /sellers/{id}:
    get:
      tags:
      - sellers
      summary: Find Seller By Id
      description: Route responsible to obtain one specific seller from the database
      parameters:
      - name: id
        in: path
        description: Seller Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    $ref: '#/components/schemas/seller'                
                  message:
                    type: string
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] sellers/id
    put:
      tags:
      - sellers
      summary: Update Seller By Id
      description: Route responsible to update one seller information
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sellerData'
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    $ref: '#/components/schemas/seller'                
                  message:
                    type: string
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] sellers/id
    delete:
      tags:
      - sellers
      summary: Delete Seller By Id
      description: Route responsible to delete one seller from the database
      parameters:
      - name: id
        in: path
        description: seller Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    $ref: '#/components/schemas/seller'                
                  message:
                    type: string
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# components
components:
  schemas:
    sellerData:
      type: object
      required:
          - name
          - cnpj
          - address
      properties:
        name:
          type: string
          description: seller Name
        cnpj:
          type: string
          description: seller Registry (CNPJ)
        address:
          type: string
          description: seller Address
    
    seller:
      type: object
      properties:
        id: 
          type: number
          description: sellers Id
        name:
          type: string
          description: seller Name
        cnpj: 
          type: string
          description: seller Registry (CNPJ)
        address: 
          type: string
          description: seller Address

schemes:
 - https
 - http
